### ISSUE TITLE
windows运行npm run run-server报错

### ISSUE THREAD

**Issue by zhangpenglink** [laoqiren/isomorphic-redux-CNode#3]
```
> isomorphic-redux-CNode@1.0.0 run-server E:\Office\ZZRNPerformance
> better-npm-run start-node-dev-server

running better-npm-run in E:\Office\ZZRNPerformance
Executing script: start-node-dev-server

to be executed: "node ./server/index.js"
Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package fr
om npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not
 yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class
environment development
come in
express-session deprecated undefined resave option; provide resave option server\app.js:96:9
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option server\app.js:96:9
the express server has been listened at port: 3000
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'E:\Office\ZZRNPerformance\logs\log_file\ZZRNPerformance_info.log-2017-11-08'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! isomorphic-redux-CNode@1.0.0 run-server: `better-npm-run start-node-dev-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the isomorphic-redux-CNode@1.0.0 run-server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2017-11-08T11_57_34_300Z-debug.log

```

**Comment by laoqiren** [comment]
试着删除日志目录`E:\Office\ZZRNPerformance\logs\log_file\`，然后根据提示看一下详细的报错日志：`C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2017-11-08T11_57_34_300Z-debug.log
`

**Comment by zhangpenglink** [comment]
@laoqiren E:\Office\ZZRNPerformance\logs\log_file\  这个项目是没有logs目录的  
npm日志如下：我觉得不是这里的问题
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'run-server' ]
2 info using npm@5.3.0
3 info using node@v8.4.0
4 verbose run-script [ 'prerun-server', 'run-server', 'postrun-server' ]
5 info lifecycle redux@1.0.0~prerun-server: redux@1.0.0
6 info lifecycle redux@1.0.0~run-server: redux@1.0.0
7 verbose lifecycle redux@1.0.0~run-server: unsafe-perm in lifecycle true
8 verbose lifecycle redux@1.0.0~run-server: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;E:\Demo\isomorphic-redux-CNode\node_modules\.bin;C:\Program Files\Docker\Docker\Resources\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\nginx-1.13.4;E:\soft\cmder_mini;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;;C:\Users\Administrator\AppData\Roaming\npm;E:\soft\Fiddler2;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps
9 verbose lifecycle redux@1.0.0~run-server: CWD: E:\Demo\isomorphic-redux-CNode
10 silly lifecycle redux@1.0.0~run-server: Args: [ '/d /s /c', 'better-npm-run start-node-dev-server' ]
11 silly lifecycle redux@1.0.0~run-server: Returned: code: 1  signal: null
12 info lifecycle redux@1.0.0~run-server: Failed to exec run-server script
13 verbose stack Error: redux@1.0.0 run-server: `better-npm-run start-node-dev-server`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid redux@1.0.0
15 verbose cwd E:\Demo\isomorphic-redux-CNode
16 verbose Windows_NT 10.0.15063
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "run-server"
18 verbose node v8.4.0
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error redux@1.0.0 run-server: `better-npm-run start-node-dev-server`
22 error Exit status 1
23 error Failed at the redux@1.0.0 run-server script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by kongchengqiu** [comment]
我 启动 时，也是这个错，这是什么原因呢？ @laoqiren @zhangpenglink
